# Private reserves suffers from the same location biases of public protected areas 

$~$

\begin{flushleft}

Francisco d’Albertas, Adrian González-Chaves, Clarice Borges-Matosa, Vitor
Zago de Almeida Paciello, Martine Maron, Jean Paul Metzger    

\end{flushleft}

$~$
$~$

\begin{flushleft}

This chapter was published as:

\end{flushleft}



\begin{flushleft}

d’ALBERTAS, F. et al. Private reserves suffer from the same location biases of public protected areas. Biological Conservation, v. 261, p. 109283, 1 set. 2021. 10.1016/j.biocon.2021.109283

\end{flushleft}

$~$
$~$


## Abstract

Setting aside areas for conservation on private properties is an essential component of the response to the biodiversity crisis. Often this is voluntary, but in Brazil, landowners are required to set aside between 20%-80% of their property for native vegetation, in what are called Legal Reserves. If degraded, they need to be restored. Alternatively, landowners can compensate for a Legal Reserve deficit on their own property by purchasing surplus credits from another property. Each landowner can define the location and spatial arrangement of their Legal Reserves within their properties, affecting the ability of the reserves to maintain biodiversity and provide ecosystem services. To identify the drivers determining the amount and location of those Legal Reserves, we accessed data for 3,622 rural properties in southeastern Brazil. We found that the likelihood of a landowner setting aside part of their farm as Legal Reserve (avoiding off-farm compensation) increased with farm size and extent of native vegetation cover, particularly where this vegetation is along rivers and steep slopes, where conserving vegetation is also mandated in what are called Areas of Permanent Protection. Properties with these characteristics located in areas of higher transportation costs and lower agricultural suitability were more likely to have the full Legal Reserve requirement within their areas. Within properties,  the location of Legal Reserves was mostly in areas of the property with low agricultural suitability, high transportation cost and close to Areas of Permanent Protection. These two results suggest landowners’ decisions are made to maximize property income and to reduce restoration costs. Conservation on private land in Brazil thus follows similar patterns to public protected areas, being mostly located on marginal land for agriculture. These areas do not necessarily provide the greatest potential biodiversity and ecosystem services benefits, suggesting that specific government interventions may be needed to encourage landowners to set aside native vegetation in ways that maximise conservation and ecosystem service outcomes.


\begin{flushleft}

\textbf{Keywords}: private-land conservation,land-regulation,environmental policy, Forest Code,
  Natural Vegetation Protection Law, Atlantic Forest

\end{flushleft}

## Introduction

One of the main policies in response to the biodiversity crisis [@cardinale_biodiversity_2012; @ipbes_unedited_2019] is the creation of new protected areas worldwide [@unep-wcmc_protected_2018]. However, the location of public protected areas show a strong bias towards lands with high elevation, steeper slopes, low agricultural productivity, and low human density, not always considering biodiversity hotspots or ecological representativeness  [@venter_bias_2018; @watson_performance_2014]. Thus, there is a clear need to reduce these biases. 

One way to reduce bias is to increase protected areas on private land [@cortes_capano_emergence_2019; @drescher_practice_2018]. Agriculture cover > 30% of the Earth’s ice-free surface [@ellis_anthropogenic_2010], mostly on private property. In turn, private properties shelter vasts amounts of native vegetation, for instance,  56% of  the United States forests [@sass_forest_2017], 28% of Europe’s forests [@pulla_mapping_2013] and 53% of the native vegetation in Brazil [@freitas_who_2017]. Protecting or enhancing natural vegetation on private properties also has benefits to private landholders beyond conservation itself. Native vegetation within farms can help increase agricultural production through the provision of ecosystem services  [@dainese_global_2019]. Natural pest control and pollination provided by native vegetation [@boesing_effects_2017; @potts_safeguarding_2016; @rand_spillover_2006] make economic contributions between US$ 10-1500 per hectare globally [@lautenbach_spatial_2012; @naranjo_economic_2015; @pimentel_economic_1997].

Some countries are implementing policies to set aside private areas for conservation in voluntary or mandatory schemes [@garibaldi_positive_2019]. Brazil, in particular, has an environmental regulation, the Native Vegetation Protection Law (Federal Law 12.651/2012), which establishes that all rural properties must have natural vegetation set aside as mandatory Areas of Permanent Protection (APP; sensitive areas such as riparian vegetation, hilltops, and steep slopes) and Legal Reserves. Legal Reserves should cover from 20% to 80% of the total property area, depending on the Country’s biome and physiognomy, and can include APP. Farmers that do not have the full area of Legal Reserves vegetated must restore it, or opt for a compensation scheme outside their property (for example, trading with landowners with Legal Reserves surplus). The latter strategy aims to allow properties with high opportunity costs to conserve or restore less valuable areas outside their limits [@may_environmental_2015]. Legal Reserves are designed for the sustainable management of ecosystem services provided by natural vegetation and can combine native and non-native species (up to 50% of Legal Reserves area). They are of vital importance for biodiversity protection, water and energy security, climate regulation, and ecosystem service provision [@metzger_why_2019]. 

At present, Legal Reserves cover 167 million ha [@metzger_why_2019], representing nearly half of the remaining native vegetation areas in Brazil [@soares-filho_cracking_2014], highlighting the importance of their maintenance. The proportion of vegetation in Legal Reserves is highest for the Atlantic Forest biome (70% of remnant vegetation), where most of the Brazilian population lives [@rezende_hotspot_2018]. Nevertheless, to achieve the objectives of Legal Reserves, their location should be adequately planned to support species survival in fragmented landscape [@fahrig_ecological_2017; @tambosi_framework_2014] while favoring ecosystem services that can increase agricultural productivity [@boesing_effects_2017; @garibaldi_stability_2011]. 

To enforce the implementation of the Native Vegetation Protection Law, in 2012 the Brazilian Government created a self-declaratory public-access database, named CAR (Portuguese acronym for environmental rural register), in which each landowner delimits the size and location of their Legal Reserves. This extensive CAR database, gathering more than 5.6 million properties and nearly 550 million ha of land (in July 2020), offers a unique opportunity to evaluate landowner’s management choices in response to a land-regulation policy.

Here we use CAR data to shed light on which drivers affect farmer's decisions about the amount and spatial location of Legal Reserves within their properties and consider the implications of their choices for biodiversity conservation and ecosystem services provision. We address two important questions: (1) which drivers predict the proportion of Legal Reserves the landowners declare inside their properties versus outside their land? (2) For landowners that decided to allocate Legal Reserves inside their properties, which drivers can predict where those Legal Reserves are located? 
Following the pattern already described for public protected areas (Venter et al., 2018; Watson et al., 2014), we expected that land management decisions concerning Legal Reserves are made to maximize farm income. Farms located in marginal areas for agriculture production or less profitable were thus expected to set aside larger proportions of Legal Reserves inside their properties. We also expected that larger properties will declare higher proportions of Legal Reserves on-property. Considering the same reasoning,  we also expected landowners will tend to locate their Legal Reserves within marginal lands. Additionally, we evaluated whether farmers are choosing to allocate Legal Reserves near existing native vegetation patches, which would increase patch size and could contribute to biodiversity conservation and ecosystem services provision.

## Methods


### Study Region

To test which drivers are affecting choices about the amount and spatial location of Legal Reserves, our sample included 164 municipalities of southeastern Brazil, in one of the most important and traditional regions for coffee production (Figure \@ref(fig:Figure1)). This region was predominantly covered by the Atlantic Rainforest, a highly biodiverse tropical forest, which suffered a long history of deforestation and fragmentation [@joly_experiences_2014]. Yet, despite past human interference, the Atlantic Forest still shelter a highly diverse set of tropical species [@mittermeier_global_2011]. For that reason, conservation policies to protect the remaining vegetation are fundamental to prevent further biodiversity losses. The study region has more than 500 thousand hectares of coffee plantations (Figure S1), with an annual harvest of 900 thousand tons, representing 15% of the country’s coffee production, and an income value of ca. 2 billion dollars [@ibge_area_2016]. Several studies have demonstrated the importance of Atlantic Forest remnants in providing key ecosystem services for coffee production, such as in modulating the flows of pollinators [@saturni_landscape_2016;gonzalez-chaves_forest_2020] or natural enemies of coffee pests [@aristizabal_landscape_2019; @libran-embid_effects_2017].
