# When do benefits from ecosystem restoration offset costs? 

$~$

\begin{flushleft}

Francisco d’Albertas, Gerd Sparovek, Luis Fernando Guedes Pinto, 
Camila Hohlenwerger, Jean Paul Metzger 

\end{flushleft}

$~$
$~$

\begin{flushleft}

This chapter was submited to Nature Sustainability and is currently under 
consideration by the editor

\end{flushleft}


$~$
$~$


## Abstract

Restoration is a critical tool for reversing biodiversity declines and mitigating climate change. However, it is a costly intervention. Where restoration provides significant financial benefits, such as by increasing crop yield or providing carbon credits, these costs may be offset. Focusing on a restoration hotspot in the Brazilian Atlantic Forest, we develop restoration scenarios and calculate estimations of their financial balance to understand conditions where restoration costs might be compensated by yield and carbon credit-derived benefits. Our study suggests that restoration costs can be offset by yield increases when farms already have >10% forest cover and restoration targets are below 25% forest cover. Current $CO_2$ price is not sufficient in offsetting net costs for higher restoration targets. A carbon value of 35-124 USD/ton would be required to promote restoration. The identification of balanced financial conditions, that create landscapes suitable for biodiversity conservation, climate mitigation, and agricultural production, has broader implications and is strategic to scale up restoration.  

## Introduction

Habitat loss [@tilman_future_2017] and climate change [@foden_identifying_2013]  threaten biodiversity globally, but clear restoration targets can greatly reduce species extinction risk [@leclere_bending_2020;@strassburg_global_2020] and simultaneously improve biodiversity conservation and human wellbeing[@barral_quantifying_2015; @benayas_enhancement_2009; @bullock_long-term_2007; @rey_benayas_restoration_2012; @shimamoto_how_2014; @wade_ecological_2008]. Many countries have made ambitious restoration commitments for the current UN decade on restoration, including to restore 350 Mha of degraded land by 2030 under the Bonn Challenge [@erbaugh_global_2020]. However, these actions face important difficulties to be implemented given the high costs involved. These include direct restoration costs, fencing and opportunity cost of forgone production.  Recent work has highlighted that these costs can act as a major financial barrier to the wide-scale adoption of restoration [@brancalion_what_2019; groot_benefits_2013].

However as well as costs, farmland restoration can also deliver ecosystem service and yield benefits, e.g. via crop pollination and pest control. In some cases, these benefits can be substantial, such as for coffee production. Several studies have demonstrated the importance of landscape native vegetation cover and the proximity between coffee fields and natural areas in modulating the flows of pollinators and natural pest controllers, which can increase coffee yield by 10 to 30% [@aristizabal_landscape_2019; @gonzalez-chaves_forest_2020; @libran-embid_effects_2017; @ricketts_economic_2004; @roubik_value_2002; @saturni_landscape_2016; @moreaux_value_2022].   Restoration also can deliver large carbon benefits. Restored tropical secondary forests have the potential to sequester an average of 3.05 tons of carbon ha-1 year-1 from the atmosphere throughout 20 years [@poorter_biomass_2016]. Carbon stock is a critical regulation service that benefits people globally and can be traded in carbon markets, helping to compensate restoration costs. Yet, from our knowledge, few studies [@bradbury_economic_2021] have incorporated the benefits of restoration in farmlands to the cost analyses, nor have they explored the situations under which these benefits may prove substantial enough to overcome costs.  Once the effects of restoration on yield and in farm income can offset at least partially restoration costs, understanding the factors that play a role in this cost/benefit balance is key to inform landowners and support decision making and agri-environmental policies. 

Here, we explore how much, and under which conditions, benefits from ecosystem restoration can offset costs. We do so in the Brazilian Atlantic Forest, a globally iconic biome [@laurance_conserving_2009], a restoration hotspot [@brancalion_global_2019], and one of the leading coffee regions of Brazil. Coffee is among the top 20 commodities traded globally 27 and Brazil is its major producer and exporter. We developed a set of scenarios with different on-farm restoration targets and calculated a detailed estimation of their financial consequences to understand how and when the costs of ecological restoration might be compensated by restoration-derived yield benefits, carbon credits, and agricultural credit lines. We have combined ecological data on how restoring natural habitats can improve ecosystem service provision with economic assessments on the balance of restoration costs and benefits. Our work can provide a framework for identifying circumstances where restoration benefits can outstrip costs, helping meet global restoration commitments and to promote restoration within agricultural landscapes.  
