# Conclusão


A erosão da biodiversidade, base de boa parte dos processos e funções ecológicas que sustentam a vida de seres humanos e não humanos representa uma crise sem precedentes em nossa curta história no planeta. Na origem desse fenômeno estão as atividades humanas, que culminaram na transformação de grande parte da superfície terrestre livre de gelo em áreas agrícolas, e na emissão de enormes quantidades de carbono na atmosfera, acelerando enormemente o processo de aquecimento global. Os dois fenômenos, a extinção de espécies e o aquecimento global se retroalimentam e exigem mudanças amplas nas sociedades humanas que dominam a geopolítica da Terra de modo a garantir um futuro habitável para as futuras gerações. 
Sem duvidas, a agricultura convencional em escala industrial, focada largamente na produção de commodities, é um dos grandes motores da rápida degradação ambiental a que testemunhamos. Este é um setor que deverá ser profundamente transformado. Porém, executar essas mudanças é um grande desafio e passará necessariamente por ferramentas de governança de cunho público e privado, que sejam capazes de conciliar os interesses econômicos dos setores produtivos envolvidos, a capacidade de prover alimentos e a manutenção e recuperação da biodiversidade em paisagens agrícolas. O Brasil, em particular, é denominado como um dos grandes celeiros do mundo e dedica uma área considerável do território à produção de “commodities”. É também um dos países mais biodiversos. Além disso, o país possui uma legislação ambiental bastante complexa (porém com uma baixa capacidade do Estado em executá-la), bem como inúmeras iniciativas de produção agrícola mais sustentável, como é o caso das certificações agrícolas. Dessa forma, o Brasil oferece uma oportunidade única de testar e aprimorar uma série de políticas direcionadas a uma produção mais sustentável, que pode servir de modelo para outras regiões.


Em cada um dos capítulos dessa tese, abordamos importantes questões permeando ferramentas de governança relacionadas ao uso da terra e à conservação da biodiversidade em paisagens agrícolas. Nossos resultados contribuem para uma melhor compreensão da adesão e impactos da legislação ambiental no Brasil e dos efeitos da certificação agrícola como uma ação complementar não governamental às políticas ambientais. 


Os resultados do capítulo 1 sugerem que as decisões de proprietários rurais com relação à alocação de áreas para conservação ou restauração de vegetação nativa dentro de propriedades rurais na Mata Atlântica – como requer a legislação vigente – são tomadas de modo a maximizar a renda da propriedade e reduzir os custos com restauração. Desse modo, sem ações específicas de incentivo para a adoção dessas áreas de “reserva”, a distribuição de vegetação nativa em áreas privadas será similar a de áreas protegidas públicas (e.g. unidades de conservação), esmagadoramente concentradas em áreas marginais para a agricultura. Esses locais não necessariamente são os mais importantes do ponto de vista da conservação e da provisão de serviços ecossistêmicos, o que acaba por reduzir a adicionalidade da lei de proteção da vegetação nativa em relação ao sistema nacional de unidades de conservação. Com ferramentas adequadas, como pagamento por serviços ambientais ou auxílio técnico, o cumprimento da lei de proteção da vegetação nativa pode fomentar sinergias entre a produção agrícola e a conservação. Porém, é preciso engajar a sociedade de maneira ampla, envolvendo agricultores, indústria e o terceiro setor.


Justamente para aumentar o entendimento sobre os reais custos implicados na restauração de áreas agrícolas e melhor informar os tomadores de decisão e fazendeiros, no capítulo 2, analisamos o balanço financeiro da restauração em propriedades rurais. Para isso, usamos a produção de café como modelo. Estimamos que para uma região tradicional de produção na Mata Atlântica, a restauração de florestas dentro das propriedades não resulta necessariamente em perdas financeiras. Dependendo da quantidade inicial de floresta na propriedade e da quantidade a ser restaurada, pode haver equilíbrio ou até ganho financeiro, por meio do aumento da provisão de serviços ecossistêmicos que elevam a produtividade agrícola. Além disso, o carbono sequestrado pode ser comercializado em mercados de crédito de carbono. No entanto, os preços praticados teriam que ser mais altos que os atuais, para que sejam competitivos com outros usos da terra. Sugerimos, portanto, que é sim possível financeiramente aliar a manutenção ou aumento da produção agrícola com maior proteção da biodiversidade e sequestro de carbono da atmosfera, mitigando os efeitos das mudanças climáticas. Entretanto, também nesse caso são necessárias políticas complementares, como a regulamentação de um mercado de carbono e o financiamento das ações de restauração, de modo a torna-las mais atrativas para os proprietários de terras. 


De fato, a atratividade de práticas de manejo sustentáveis é uma questão chave para que mudanças reais aconteçam. A adoção voluntária de boas práticas agrícolas vem crescendo globalmente e visa atender a esse anseio. A certificação agrícola oferece justamente a perspectiva de uma melhor remuneração dos produtores, em troca de uma série de regras visando melhorias socioeconômicas e ambientais. Aliada à regulamentação provida pela legislação ambiental, ela pode ser mais um instrumento que potencializa mudanças no campo. Assim, no capitulo 3, nos debruçamos sobre a efetividade da certificação de café em promover ganhos para a conservação. Nos focamos em métricas objetivas, como o desmatamento, a regeneração de vegetação nativa e o cumprimento da legislação ambiental em propriedades certificadas, quando comparadas com propriedades não certificadas. Encontramos que a certificação de café em uma região de agricultura consolidada não teve um efeito detectável em reduzir o desmatamento ou em aumentar a taxa de regeneração de vegetação nativa. Entretanto, vimos que a certificação pode servir realmente como um estímulo adicional para o cumprimento da legislação ambiental. Em particular, a recuperação de áreas ambientalmente sensíveis, como topos de morro e áreas ripárias, foi maior nas propriedades certificadas quando comparadas com propriedades não certificadas da mesma região. Esses resultados sugerem que o impacto da certificação para a conservação pode ainda ser expandido, seja pela sua ampla adoção em áreas de fronteiras agrícolas (onde a pressão de conversão de usos da terra é maior), seja explorando mais sinergias da certificação com o cumprimento da legislação ambiental.


Em conclusão, conseguimos satisfazer nossos objetivos iniciais e compreender melhor como o processo de alocação de vegetação nativa em propriedades rurais está sendo feito, o balanço de custos e benefícios envolvidos, e a efetividade de ferramentas voluntárias em fomentar o cumprimento da legislação ambiental. Restam ainda muitas questões em aberto, como a transposição dos resultados encontrados para um contexto de aplicação prática. No entanto, esperamos que as discussões trazidas pelo trabalho auxiliem a desmobilizar argumentos simplistas que insistem em uma dicotomia entre a economia e o meio ambiente. Longe de apontar soluções simples, buscamos compreender as potencialidades e limitações de instrumentos já existentes, além de sinalizar caminhos possíveis para aprimoramento. Os resultados desta tese são importantes não apenas para balizar políticas públicas no Brasil, com enfoque na área ambiental, mas são também relevantes em um contexto muito mais amplo, em que existe um esforço global por ações efetivas que lidem com a perda de biodiversidade e os impactos das mudanças climáticas. 


